
package Formularios;

import Classes.Dados;
import Classes.Opcoes;
import Classes.Utilidades;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class frmFatura extends javax.swing.JInternalFrame {
    private Dados msDados;
    private DefaultTableModel mTabela;
    
    
    public void setDados(Dados msDados){
        this.msDados = msDados;
    }
    
    public frmFatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbProduto = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalhes = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnDeletarTodos = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnPesqCliente = new javax.swing.JButton();
        btnPesqProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nova Venda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Data :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Cliente :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Produto :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Quantidade :");

        txtData.setEnabled(false);

        tblDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalhes);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Adicionar Venda.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar Venda");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excluir Venda.png"))); // NOI18N
        btnDeletar.setToolTipText("Excluir Venda");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnDeletarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excluir.png"))); // NOI18N
        btnDeletarTodos.setToolTipText("Excluir todas as vendas");
        btnDeletarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTodosActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pesquisar.png"))); // NOI18N
        btnPesqCliente.setToolTipText("Pesquisar Cliente");
        btnPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqClienteActionPerformed(evt);
            }
        });

        btnPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pesquisar.png"))); // NOI18N
        btnPesqProduto.setToolTipText("Pesquisar Produto");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/moeda-de-dinheiro.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("TOTAL :");

        txtQuant.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuant.setToolTipText("Quantidade Vendida");
        txtQuant.setEnabled(false);

        txtValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValor.setToolTipText("Valor das vendas");
        txtValor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnDeletarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCliente, 0, 267, Short.MAX_VALUE)
                                    .addComponent(cmbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnPesqCliente)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesqProduto))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeletar)
                            .addComponent(btnDeletarTodos)
                            .addComponent(btnSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Opcoes opc = new Opcoes("advan.who@gmail.com", "Selecione um Cliente");
        cmbCliente.addItem(opc);
        for (int i = 0; i <msDados.numeroClientes(); i++) {
            opc = new Opcoes(
            msDados.getClientes()[i].getIdCliente(),
            msDados.getClientes()[i].getNome()+""+
            msDados.getClientes()[i].getSobrenome());
            cmbCliente.addItem(opc);
            
        }
        
        opc = new Opcoes("advan.who@gmail.com", "Selecione um Produto");
        cmbProduto.addItem(opc);
        for (int i = 0; i <msDados.numeroProdutos(); i++) {
            opc = new Opcoes(
            msDados.getProdutos()[i].getIdProduto(),
            msDados.getProdutos()[i].getDescricao());
            cmbProduto.addItem(opc);
            
        }
        
        txtData.setText(Utilidades.formatDate(new Date()));
        txtQuant.setText("0");
        txtValor.setText("0");
        
        preencherTabela();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
            if(cmbProduto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor, selecionar um produto.");
            cmbProduto.requestFocusInWindow();
            return;
            }
            if(txtQuantidade.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Favor, digitar uma quantidade.");
            txtQuantidade.requestFocusInWindow();
            return;
            }
            
            if(!Utilidades.isNumeric(txtQuantidade.getText())){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar somente números");
            txtQuantidade.setText("");
            txtQuantidade.requestFocusInWindow();
            return;
        }
            
            int quantidade = Integer.parseInt(txtQuantidade.getText());
            if(quantidade <= 0){
            JOptionPane.showMessageDialog(rootPane, "Favor digitar um número maior que zero");
            txtQuantidade.setText("");
            txtQuantidade.requestFocusInWindow();
            return;
        }
            int pos = msDados.posicaoProduto(((Opcoes)cmbProduto.getSelectedItem()).getValor());
           
            String registro[] = new String[5];
            registro[0]=msDados.getProdutos()[pos].getIdProduto();
            registro[1]=msDados.getProdutos()[pos].getDescricao();
            registro[2]=""+ msDados.getProdutos()[pos].getPreco();
            registro[3]=""+ quantidade;
            registro[4]=""+ (quantidade * msDados.getProdutos()[pos].getPreco());
            mTabela.addRow(registro);
            
            cmbProduto.setSelectedIndex(0);
            txtQuantidade.setText("");
            cmbProduto.requestFocusInWindow();
            totais();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(cmbCliente.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane,"Favor, selecionar um cliente.");
            cmbCliente.requestFocusInWindow();
            return;
        }
        int totalquant = new Integer(txtQuant.getText());
        if(totalquant==0){
            JOptionPane.showMessageDialog(rootPane,"Favor, inserir todos os dados para a venda!");
            cmbProduto.requestFocusInWindow();
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente realizar esta venda?");
        if(resposta != 0){
            return;
        }
        
        int numFatura = msDados.getNumeroFatura()+1;
        FileWriter fw = null;  
        PrintWriter pw = null;
      try {
          fw = new FileWriter("Data/Fatura.txt", true);
          pw = new PrintWriter(fw);
          
          String aux = "1|"
                  + numFatura +"|"
                  +((Opcoes)cmbCliente.getSelectedItem()).getValor()+"|"
                  +((Opcoes)cmbCliente.getSelectedItem()).getDescricao()+"|"
                  + txtData.getText();
          pw.println(aux);
                  
          int num = tblDetalhes.getRowCount();
          for(int i = 0; i < num; i++){
               aux = "2|"
               + Utilidades.objectToString(tblDetalhes.getValueAt(i, 0))+"|"
               + Utilidades.objectToString(tblDetalhes.getValueAt(i, 1))+"|"
               + Utilidades.objectToString(tblDetalhes.getValueAt(i, 2))+"|"
               + Utilidades.objectToString(tblDetalhes.getValueAt(i, 3))+"|"
               + Utilidades.objectToString(tblDetalhes.getValueAt(i, 4));
               
              pw.println(aux);
               
         }
      } catch (Exception e1) {
          e1.printStackTrace();
      }finally{
          try {
              if(fw != null){
                  fw.close();
              }
          } catch (Exception e2) {
              e2.printStackTrace();
          }
      }
          JOptionPane.showMessageDialog(rootPane,
           "VENDA:"+numFatura+"VENDA REALIZADA COM SUCESSO!");
           msDados.setNumeroFatura(numFatura);
           cmbCliente.setSelectedIndex(0);
           LimparTabela();
           totais();
           cmbCliente.requestFocusInWindow();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeletarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTodosActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja deletar esta venda?");
        if(resposta != 0){
            return;
        }
        LimparTabela();
        totais();
    }//GEN-LAST:event_btnDeletarTodosActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(cmbProduto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Favor, selecionar um produto.");
            cmbProduto.requestFocusInWindow();
            return;
            }
        try {
            DefaultTableModel modelo = (DefaultTableModel)tblDetalhes.getModel();
            int Linha = tblDetalhes.getRowCount();
            for(int i = 0 ; Linha > i; i++){
                String idTabela = Utilidades.objectToString(tblDetalhes.getValueAt(i,0));
                String idCombo = ((Opcoes)cmbProduto.getSelectedItem()).getValor();
                if(idTabela.equals(idCombo)){
                modelo.removeRow(i);
                totais();
                return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqClienteActionPerformed
        frmPesqCliente mPesqCliente = new frmPesqCliente(null, closable);
        mPesqCliente.setDados(msDados);
        mPesqCliente.setLocationRelativeTo(null);
        mPesqCliente.setVisible(true);
       
    }//GEN-LAST:event_btnPesqClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDeletarTodos;
    private javax.swing.JButton btnPesqCliente;
    private javax.swing.JButton btnPesqProduto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cmbCliente;
    private javax.swing.JComboBox<Object> cmbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalhes;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
        
     private void preencherTabela(){
        String titulos[] = {"ID PROD","DESC","PREÇO","QTDE","VALOR"};
        String registro[] = new String [5];
        mTabela = new DefaultTableModel(null, titulos);
        tblDetalhes.setModel(mTabela);
        
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblDetalhes.getColumnModel().getColumn(2).setCellRenderer(dtcr);
        tblDetalhes.getColumnModel().getColumn(3).setCellRenderer(dtcr);
        tblDetalhes.getColumnModel().getColumn(4).setCellRenderer(dtcr);
        }
     private void totais(){
         int num = tblDetalhes.getRowCount();
         int somaQuant = 0, somaValor =0;
         for(int i = 0; i < num; i++){
             somaQuant += Utilidades.objectToInt(tblDetalhes.getValueAt(i, 3));
             somaValor += Utilidades.objectToInt(tblDetalhes.getValueAt(i, 4));
         }
         txtQuant.setText(""+somaQuant);
         txtValor.setText(""+somaValor);
     }  
     
    public void LimparTabela(){
        try {
            DefaultTableModel modelo = (DefaultTableModel)tblDetalhes.getModel();
            int Linha = tblDetalhes.getRowCount();
            for(int i = 0; Linha> i; i++){
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
   
